<a href="https://colab.research.google.com/github/hug627/streamlit-for-30-days/blob/main/Artificial_Neural_Network_Checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# how to load  MNIST Dataset
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
print(x_train.shape)

(60000, 28, 28)


In [3]:
# Normalize feature data.
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
# Encode categorical labels.
y_train_encoded = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test_encoded = tf.keras.utils.to_categorical(y_test, num_classes=10)

print(y_train_encoded.shape)

(60000, 10)


In [5]:
# Split the data into training and testing sets.
from sklearn.model_selection import train_test_split

# Since MNIST is already split, this is for demonstration purposes
# In a real scenario, you would use this on a combined dataset
# x_train, x_test, y_train_encoded, y_test_encoded = train_test_split(
#     x, y_encoded, test_size=0.2, random_state=42
# )
# print(x_train.shape, x_test.shape, y_train_encoded.shape, y_test_encoded.shape)
print("MNIST dataset is already split into training and testing sets.")

MNIST dataset is already split into training and testing sets.


In [16]:
# Reshape the 28x28 images into flat 784-pixel array
x_train_flat = x_train.reshape(x_train.shape[0], -1)
print(x_train_flat)
x_test_flat = x_test.reshape(x_test.shape[0], -1)
print(x_test_flat)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
# Normalize pixel values to range between 0 and 1.
x_train_flat = x_train_flat / 255.0
print(x_train_flat)
x_test_flat = x_test_flat / 255.0
print(x_test_flat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
# Convert labels into one-hot encoded vectors.
y_train_encoded = tf.keras.utils.to_categorical(y_train, num_classes=10)
print(y_train_encoded)
y_test_encoded = tf.keras.utils.to_categorical(y_test, num_classes=10)
print(y_test_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
# Optionally, create a validation set to aid in hyperparameter tuning.
x_train_flat, x_val_flat, y_train_encoded, y_val_encoded = train_test_split(
    x_train_flat, y_train_encoded, test_size=0.2, random_state=42
)

In [20]:
# Input Layer: Adjust to match the number of input features (784 for MNIST)
input_layer = tf.keras.layers.Input(shape=(784,))
print(input_layer)

<KerasTensor shape=(None, 784), dtype=float32, sparse=False, ragged=False, name=keras_tensor_2>


In [21]:
# Hidden Layers: Include at least one hidden layer with 'relu' activation. Additional layers may be added to increase model complexity.
hidden_layer1 = tf.keras.layers.Dense(128, activation='relu')(input_layer)
print(hidden_layer1)

<KerasTensor shape=(None, 128), dtype=float32, sparse=False, ragged=False, name=keras_tensor_3>


In [22]:
# Output Layer: Use 'softmax' activation for Iris and 'sigmoid' for binary classification tasks like MNIST (if treated as binary).
output_layer = tf.keras.layers.Dense(10, activation='softmax')(hidden_layer1)
print(output_layer)

<KerasTensor shape=(None, 10), dtype=float32, sparse=False, ragged=False, name=keras_tensor_4>


In [23]:
# Optimizer: 'adam' for reliable performance across both datasets.
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
print(optimizer)

In [24]:
# Loss Function: Use 'categorical_crossentropy' for multi-class tasks (MNIST); 'binary_crossentropy' for binary classification.
loss_function = 'categorical_crossentropy'
print(loss_function)

categorical_crossentropy


In [25]:
# Metrics: Focus on 'accuracy' as the primary metric.
metrics = ['accuracy']
print(metrics)


['accuracy']


In [26]:
# Train the model using the training data, while utilizing the validation set to monitor performance.

# Build the model (assuming input_layer, hidden_layer1, and output_layer are defined in previous cells)
model = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

# Compile the model (assuming optimizer, loss_function, and metrics are defined in previous cells)
model.compile(optimizer=optimizer,
              loss=loss_function,
              metrics=metrics)

# Train the model
history = model.fit(x_train_flat, y_train_encoded, epochs=10, validation_data=(x_val_flat, y_val_encoded))

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8620 - loss: 0.4800 - val_accuracy: 0.9537 - val_loss: 0.1634
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9590 - loss: 0.1422 - val_accuracy: 0.9626 - val_loss: 0.1233
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9726 - loss: 0.0937 - val_accuracy: 0.9712 - val_loss: 0.0980
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9796 - loss: 0.0681 - val_accuracy: 0.9707 - val_loss: 0.0973
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9847 - loss: 0.0500 - val_accuracy: 0.9756 - val_loss: 0.0820
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9900 - loss: 0.0372 - val_accuracy: 0.9714 - val_loss: 0.0966
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9909 - loss: 0.0322 - val_accuracy: 0.9754 - val_loss: 0.0843
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9938 - loss: 0.0221

In [31]:
# Adjust training parameters such as epochs and batch size based on validation outcomes.
history = model.fit(x_train_flat, y_train_encoded, epochs=10, validation_data=(x_val_flat, y_val_encoded))


Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9966 - loss: 0.0124 - val_accuracy: 0.9767 - val_loss: 0.0917
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9960 - loss: 0.0118 - val_accuracy: 0.9778 - val_loss: 0.0886
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9984 - loss: 0.0072 - val_accuracy: 0.9768 - val_loss: 0.0999
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9979 - loss: 0.0077 - val_accuracy: 0.9778 - val_loss: 0.0900
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9982 - loss: 0.0069 - val_accuracy: 0.9772 - val_loss: 0.0954
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9983 - loss: 0.0060 - val_accuracy: 0.9783 - val_loss: 0.1010
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9987 - loss: 0.0048 - val_accuracy: 0.9784 - val_loss: 0.1034
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9984 - loss: 0.0053 -

In [28]:
# Evaluate the model on the test data.
loss, accuracy = model.evaluate(x_test_flat, y_test_encoded)

print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9715 - loss: 0.1019
Test Loss: 0.08459848910570145
Test Accuracy: 0.9771999716758728


In [30]:
# Utilize detailed metrics such as the confusion matrix and classification report for more comprehensive insights.
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Get predictions from the model
y_pred = model.predict(x_test_flat)

# Convert predictions and true labels to class indices
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test_encoded, axis=1)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test_classes, y_pred_classes)
print("Confusion Matrix:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test_classes, y_pred_classes)
print("\nClassification Report:")
print(class_report)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Confusion Matrix:
[[ 967    1    2    0    1    1    6    1    1    0]
 [   0 1125    4    1    0    1    2    1    1    0]
 [   3    2 1012    3    1    0    2    4    4    1]
 [   1    0    7  965    0   15    1    7    7    7]
 [   1    0    3    1  960    0    5    2    1    9]
 [   2    0    0    2    1  874    7    2    3    1]
 [   2    2    2    1    3    4  944    0    0    0]
 [   1    4   10    1    1    0    0 1004    4    3]
 [   5    1    3    3    1    7    3    4  944    3]
 [   0    3    0    2    7    3    0   11    6  977]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.98      1032
           3       0.99      0.96      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.97      0.98      0.97       892
       